### Makefile --- 
## 
## Filename     : Makefile
## Description  : Makefile for the SHT2X module.
## Author       : Christophe Burki
## Maintainer   : Christophe Burki
## Created      : Mon Sep 15 20:58:53 2014
## Version      : 1.0.0
## Last-Updated : Mon Sep 15 21:03:08 2014 (7200 CEST)
##           By : Christophe Burki
##     Update # : 7
## URL          : 
## Keywords     : 
## Compatibility: 
## 
######################################################################
## 
### Commentary   : 
## 
## 
## 
######################################################################
## 
### Change log:
## 
## 
######################################################################
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License version 3 as
## published by the Free Software Foundation.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; see the file LICENSE.  If not, write to the
## Free Software Foundation, Inc., 51 Franklin Street, Fifth
## ;; Floor, Boston, MA 02110-1301, USA.

## 
######################################################################
## 
### Code         :

TARGET := test_sht2x
MODULE := module_sht2x
SOURCES := $(MODULE).cpp test_sht2x.c

include ../Config.mk
include $(GNUBLINMKDIR)/gnublin.mk

######################################################################
### Makefile ends here
